refactor: Enhance configure script with improved error handling and new build options

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,42 +1,233 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 
-set -e
-
-# Check if a package is installed
-function check_installed () { dpkg -s "$1" &>/dev/null ; }
+set -eo pipefail
 
 function reset_env () {
+
     rm -rv debian/.* debian/"$(basename "$(pwd)")" \
-        debian/"$(basename "$(pwd)")".* debian/files \
-        debian/{changelog,changelog.gz} 2>/dev/null || true
+        debian/files \
+        debian/{changelog,changelog.gz} 2>/dev/null \
+        debian/*.substvars \
+        debian/*.ex \
+        debian/*.debhelper \
+        man/"$(basename "$(pwd)")".{1,conf.5,8} \
+        doc/version || true
+
+        # shellcheck disable=SC2181
+        if [ "$?" -eq 0 ] ; then
+            echo -e "Environment reset successfully $_pass"
+        else
+            echo -e "Failed to reset the environment $_fail"
+            exit 1
+        fi
 }
 
-function install_theme () {
+function build_deb () {
 
-    local _install_theme_dir _install_doc
+    local _arch _no_sign _key _root_command
 
-    _install_doc="/usr/share/grub/themes/polka-dots-dark"
-    _install_theme_dir="/usr/share/grub/themes/polka-dots-dark"
+    _sign_key=
+    _no_sign=""
+    _target_arch=( "$(dpkg --print-architecture)" )
+    _root_command=fakeroot
+    _arches=()
 
-    mkdir -p "$_install_theme_dir/{fonts,images,icons}" \
-        "$_install_doc" ||
+    # Manually required system packages
+    _required=( debhelper dh-make git dh-gitchangelog pandoc coreutils )
+    _missing=()
 
-    install -vm 666 theme.txt "$_install_theme_dir/"
-    install -vm 666 screenshot.png "$_install_theme_dir/screenshot.png"
-    install -vm 666 copyright.images "$_install_theme_dir/"
+    shift
 
-    install -vm 666 COPYING "$_install_doc/copyright"
-    install -vm 666 README.md "$_install_doc/"
-    install -vm 666 CODE_OF_CONDUCT.md "$_install_doc/"
-    install -vm 666 docs/version "$_install_doc/version"
+    while [ $# -gt 0 ] ; do case "$1" in
+            --build-type            )
+                case "$2" in
+                    binary|source|full )
+                        _type="$2" ; shift ;;
+                    *                  )
+                        echo "Invalid build type: $2" ; exit 1
+                ;;
+                esac
+            ;;
+            --sign-key              ) _key="$2" ; shift ;;
+            --no-sign               ) _no_sign="--no-sign" ;;
+            --root-command          )
+                case "$2" in
+                    fakeroot|sudo|super|really )
+                        _root="--root-command=$_root_command" ;;
+                    *                          )
+                        echo "Invalid root command: $2" ; exit 1
+                    ;;
+                esac
+            ;;
+            --*                     ) echo "Unknown option: $1" ; exit 1 ;;
+        esac ; shift ; done
 
-    install -vm 666 fonts/* "$_install_theme_dir/fonts/"
-    install -vm 666 images/* "$_install_theme_dir/images/"
-    install -vm 666 icons/* "$_install_theme_dir/icons/"
+    # If no --target-arch was provided, use the default architecture
+    if [ -n "$_no_sign" ] && [ -n "$_key" ] ; then
+        echo "$_waring The --sign-key option is ignored because --no-sign is set."
+        _sign_key=""
+    fi
+
+    if [ -n "$_key" ] ; then
+        if ! gpg --list-keys "$_key" &>/dev/null ; then
+            echo "$_fail GPG key $_key not found."
+            exit 1
+        fi
+        _sign_key="--sign-key=$_key"
+    fi
+
+    if [ ! -d "debian" ] ; then
+        echo "The debian directory is missing. Please run \`dh_make\` first."
+        exit 1
+    fi
+
+    # Check if the HowToNebie APT repository is available
+    if ! grep -qr "howtonebie" /etc/apt/ 2>/dev/null; then
+        echo -e "$_missingRepo"
+    else
+        echo -e "configure: Detected HowToNebie APT repository."
+    fi
+
+    for pkg in "${_required[@]}"; do
+        if dpkg -s "$pkg" &>/dev/null "$pkg"; then
+            echo -e "configure: Checking for $pkg $_pass"
+        else
+            echo -e "configure: Checking for $pkg $_fail"
+            _missing+=( "$pkg" )
+        fi
+    done
+
+    # If _missing is not empty, print a message and exit
+    if [ ${#_missing[@]} -ne 0 ]; then
+        echo -e "configure: The following packages are missing:\n"
+        for pkg in "${_missing[@]}"; do echo -e "  - $pkg" ; done
+        echo -e "\nPlease install them using your package manager (e.g. \`sudo apt install <package>\`)"
+        exit 1
+    fi
+
+    if [ -d man ] ; then
+        for m in man/*.md; do
+            base=$(basename "$m" .md)
+            out="man/${base}"
+            pandoc "$m" -s -t man -o "$out"
+        done
+    fi
+
+    dh_gitchangelog
+
+    if [ "$_type" = "source" ] || [ "$_type" = "full" ] ; then
+        # Compress the source package into a tarball
+        _version=$(cat doc/version)
+        cd ../ ; tar -czf "${_app_name}_$_version.orig.tar.gz" "$_app_name"
+        cd "$_app_name"
+    fi
+
+
+    for arch in "${_target_arch[@]}"; do
+        # shellcheck disable=SC2086
+        dpkg-buildpackage ${_root} ${_no_sign} ${_sign_key} --target-arch "$arch" --build=${_type:-binary}
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then
+            echo -e "$_fail Failed to build package for architecture: $arch"
+            exit 1
+        else
+            echo -e "$_pass Successfully built package for architecture: $arch"
+        fi
+    done
 
 }
 
+function manual_install () {
+
+    echo "Installing the application..."
+
+    # shellcheck disable=SC1091
+    source /etc/os-release || { echo "Missing /etc/os-release file." ; exit 1 ; }
+
+    echo -e "Detected OS: \033[1m$NAME\033[0m\n"
+
+    (( "$(id -u)" == 0 )) || { echo "$_rootInstructions" ; exit 1 ; }
+
+    install -vm 644 -D "$_app_conf" "$_etc_dir/"
+    install -vm 644 -D "$_app" "$_app_bin/"
+    install -vm 644 -D "$_app_service" "$_systemd_dir/"
+    install -vm 644 -D "$_app_completion" "$_bash_completion/"
+    install -vm 644 -D "$_copyright" "$_docs/"
+    install -vm 644 -D "$_readme" "$_docs/"
+    install -vm 644 -D "$_coc" "$_docs/"
+    install -vm 644 -D "$_version" "$_docs/"
+
+    if command -v pandoc &>/dev/null ; then
+        for m in man/*.md; do
+            base=$(basename "$m" .md)
+            out="${BUILD_DIR}/usr/share/man/man8/${base}"
+            pandoc "$m" -s -t man -o "$out"
+            gzip -f9 "$out"
+            echo "Installed manpage: $out.gz"
+        done
+    else
+        echo -e "configure: pandoc is not installed. Skipping manpage generation."
+    fi
+
+    echo ""
+
+    # enable the service
+    # shellcheck disable=SC2086
+    case "$(systemctl is-enabled $_app_name.service)" in
+        enabled|static                  )
+            echo -e "\033[32mService $_app_name is already enabled.\033[0m"
+        ;;
+        disabled|inactive               )
+            echo -e "\033[33mEnabling service $_app_name...\033[0m"
+            systemctl enable --now "$_app_name.service"
+        ;;
+        dead|failed)
+            echo -e "\033[31mService $_app_name is dead or failed.\033[0m"
+            echo -e "Please check the service status with \`systemctl status $_app_name.service\`"
+            exit 1
+        ;;
+        not-found|unknown               )
+            echo -e "\033[31mService $_app_name does not exist.\033[0m"
+            exit 1
+        ;;
+        *                               )
+            echo -e "\033[31mService $_app_name is not enabled.\033[0m"
+        ;;
+    esac
+
+}
+
+set -eo pipefail
+
+_app_name="$(basename "$(pwd)")"
+
+# Directories where the files will be installed
+
+_etc_dir="/etc/default"
+_docs="/usr/share/doc/$_app_name"
+_app_bin="/usr/bin"
+_bash_completion="/usr/share/bash-completion/completions"
+_man="/usr/share/man/man1"
+_systemd_dir="/usr/lib/systemd/system"
+
+# Files to be installed
+_app="$_app_name"
+_app_conf="$_app_name.conf"
+_app_service="$_app_name.service"
+_app_completion="completion/$_app_name"
+_copyright="COPYING"
+_readme="README.md"
+_coc="CODE_OF_CONDUCT.md"
+_version="docs/version"
+_app_man="man/$_app_name.1.md"
+_conf_man="man/$_app_name.conf.5.md"
+
+_gpg_id=""
 _sign=true
+
+_pass="[\033[32m\u2714\033[0m]"
+_fail="[\033[31mx\033[0m]"
+_waring="[\033[33m!\033[0m]"
 
 _rootInstructions="$(cat <<-EOF
 To install this package, you need to run this script as root.
@@ -44,96 +235,59 @@ EOF
 )"
 
 _helpInfo="$(cat <<-EOF
-Configure script for the Polka-Dots Dark GRUB theme.
+Configure script for $_app_name - A Btrfs snapshot management tool.
 
-Usage: $0 [options]
+Usage: $0 [options] flags ARG..
 
 Options:
-  --no-sign         Do not sign the package. The default is to setup for
-                    building a signed package. The build will fail if there
-                    is no GPG key available.
+    build           Build the DEB package using dpkg-buildpackage. if no other
+                    options are specified the build may fail.
 
-  --init            Initialize the build environment.
-  --install         Install the theme to the system.
-  --reset           Reset the build environment.
-  --help, -h        Show this help message and exit.
+    install         Install the application, useful for non Debian/Ubuntu systems.
+                    This option requires root privileges.
 
+    reset           Reset the build environment.
+
+    help            Show this help message and exit.
+
+Build Flags:
+    --build-type TYPE
+                    Specify the build type. Valid values are: binary, source, full.
+                    Default is binary.
+
+    --sign-key GPG_ID
+                    Specify the GPG key ID to sign the package. If not specified,
+                    the package will not be signed.
+
+    --no-sign       Do not sign the package. Overrides --sign-key.
+
+    --root-command COMMAND
+                    Specify the command to run as root. Valid values are: fakeroot,
+                    sudo, super, really. Default is fakeroot.
+
+Examples:
+    $0 build --build-type binary
+    $0 build --no-sign --root-command sudo
 EOF
 )"
 
-# shellcheck disable=SC2221
-# shellcheck disable=SC2222
-while true ; do
-    case "$1" in
-        --no-sign                   ) _sign=false                                ;;
-        --init                      ) echo "Setting up the build environment..." ;;
-        --install                   )
-            (( "$(id -u)" == 0 )) || { echo "$_rootInstructions" ; exit 1 ; }
-            install_theme || { echo "Failed to install theme." ; exit 1 ; }
-            exit 0
-        ;;
-        --reset                     ) reset_env                         ; exit 0 ;;
-        --help                      ) echo -e "$_helpInfo"              ; exit 0 ;;
-        --*                         ) echo "Unknown option: $1"         ; exit 1 ;;
-    esac
-    shift
-    [ -z "$1" ] && break
-done
+_missingRepo="$(cat <<-EOF
+HowToNebie APT repository is not available on your system.
 
+Please add the HowToNebie APT repository to your system.
+You can find instructions here: https://repository.howtonebie.com
+After adding the repository to your system, run:
 
-_pass="[\033[32m\u2714\033[0m]"
-_fail="[\033[31mx\033[0m]"
+    sudo apt update\033[0m - Then run this script again."
+EOF
+)"
 
-# Manually required system packages
-_required=( dpkg-changelog git debhelper dh-make lintian )
-
-_missing=()
-
-echo -e "Configuring build environment...\n"
-
-# Check if the HowToNebie APT repository is available
-if ! grep -q "howtonebie" /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null; then
-    echo -e "\033[31mHowToNebie APT repository is not available.\033[0m"
-    echo -e "Please add the HowToNebie APT repository to your system."
-    echo -e "You can find instructions here: https://repository.howtonebie.com"
-    echo -e "After adding the repository to your system, run:"
-    echo -e "\033[1m  sudo apt update\033[0m"
-    echo -e "Then run this script again."
-    exit 1
-else
-    echo -e "\033[32mHowToNebie APT repository is available.\033[0m\n"
-fi
-
-echo -e "🔍 Checking for build requirements\n"
-for pkg in "${_required[@]}"; do
-    if check_installed "$pkg"; then
-        echo -e "$pkg $_pass"
-    else
-        echo -e "$pkg $_fail"
-        _missing+=("$pkg")
-    fi
-    sleep 0.33
-done
-
-# If _missing is not empty, print a message and exit
-if [ ${#_missing[@]} -ne 0 ]; then
-    echo -e "\n\n\033[31mThe following packages are missing:\033[0m"
-    for pkg in "${_missing[@]}"; do
-        echo -e "  - $pkg"
-    done
-    echo -e "\nPlease install them using your package manager (e.g., apt, dnf, or pacman).\n"
-    echo -e "For example, you can run:\n"
-    echo -e "\033[1m  sudo apt install ${_missing[*]}\033[0m\n"
-    echo -e "After installing the missing packages, run this script again.\n"
-    exit 1
-fi
-
-dpkg-changelog
-
-if test "$_sign" = true; then
-    echo -e "\nuse \`dpkg-buildpackage --build=binary  --sign-keyid=[key-id] --root-command=fakeroot\` to build signed package"
-else
-    echo -e "\nuse \`dpkg-buildpackage --build=binary --root-command=fakeroot\` to build the package without signing"
-fi
+case "$1" in
+    build                     ) build_deb "$@"                     ;;
+    install                   ) manual_install                     ;;
+    reset                     ) reset_env                          ;;
+    help                      ) echo -e "$_helpInfo"               ;;
+    *                         ) echo "Unknown option: $1" ; exit 1 ;;
+esac
 
 exit 0
